name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependecies
        run: npm install
      - name: Generate report
        run: npm run lint:report
        continue-on-error: true
      - name: Annotate report
        uses: ataylorme/eslint-annotate-action@1.0.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint-report.json"
      - name: Archive report
        uses: actions/upload-artifact@v1
        with:
          name: eslint-report.json
          path: eslint-report.json
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependecies
        run: npm install
      - name: Lint
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: check

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - name: Archive build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
  deploy:
     runs-on: ubuntu-latest
     needs: build
     
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Download build
         uses: actions/download-artifact@v1
         with:
           name: build
       - name: Init firebase
         run: echo "${{ secrets.FIREBASERC }}" > .firebaserc
       - name: Deploy to firebase
         uses: w9jds/firebase-action@master
         with:
           args: deploy --project ${{secrets.FIREBASE_PROJECT}}
         env:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 
